README.md
tax_microdata_benchmarking/create_flat_file.py
tax_microdata_benchmarking/examination/results2.md
tax_microdata_benchmarking/examination/taxcalculator/xb23-23.res-expect
tax_microdata_benchmarking/examination/taxcalculator/xb26-26.res-expect

This PR adds tax revenue and tax expenditure estimates generated by Tax-Calculator (version 3.5.3) using Phase2 (v7) input datasets for 2023 and for 2026.

Add examination results for Phase2 datasets

---

tests/test_flat_file.py

Fixes #58 
Fixes #57 
We now get 253bn for medical expenses (compared to 215bn in tax-data) which seems reasonable.
We also get 33bn for unemployment compensation. Tax-data has 200bn but that's clearly COVID-related, and it seems like 30bn is close to the steady-state value.
I've added two explicit tests for these variables.

Add explicit tests for medical expense and unemployment compensation

---

.gitignore
tax_microdata_benchmarking/create_taxcalc_input_variables.py
tax_microdata_benchmarking/create_taxcalc_sampling_weights.py
tests/test_flat_file.py

Add test of creating the `tmd.csv` file and whether or not the calibrated pass-through W-2 wages scale parameter value is consistent with the value used in the reweighting process.

Add test_create_taxcalc_tmd_file

---

setup.py

Require newest version of Tax-Calcuator that includes `tmd_weights.csv.gz` and `growfactors.csv` extending out through 2074.

Require taxcalc>=3.6 in setup.py

---

setup.py

Among other things Tax-Calculator 4.0 allows use of custom growfactors CSV files.

Update setup.py to require taxcalc 4.0.0+

---

tax_microdata_benchmarking/create_taxcalc_growth_factors.py
tax_microdata_benchmarking/examination/taxcalculator/tmd-26.res-expect

Update the `create_taxcalc_growth_factors.py` script to generate a tmd-specific growfactors file.  And use the newly revised Tax-Calculator (that uses the new tmd-specific growfactors file) to redo the 2023 and 2026 examination runs as a check that nothing of significance changes.

Revise create_taxcalc_growth_factors.py to generate a tmd_growfactors.csv file

---

setup.py

Use of `policyengine-us` packages consistent with the old `setup.py` version number cause errors after the merge of pull request #90 (which forgot to do this update of `setup.py`).
An example of the errors encountered when using older `policyengine-us` packages is [here](https://github.com/PSLmodels/tax-microdata-benchmarking/issues/93#issuecomment-2178685213).   That error mentions a missing Tax-Calculator `estate_income` variable that was added just a few days ago (2024-06-18) in `policyengine-us` version 0.790 via [Policyengine-US PR 4655](https://github.com/PolicyEngine/policyengine-us/pull/4655).

Fix setup.py to include correct required policyengine-us version

---

tax_microdata_benchmarking/datasets/tmd.py
tax_microdata_benchmarking/utils/trace.py

Add tracing capability (that can be turned on or off) to track what is happening with weights and  W2-wages during the construction of the 2021 file in the `datasets/tmd.py` module.
This is an initial version that will probably be enhanced as we learn more about the details of the `tmd.py` data construction process.

Add utils/trace.py module and use in datasets/tmd.py module

---

tax_microdata_benchmarking/create_taxcalc_input_variables.py
tax_microdata_benchmarking/utils/soi_replication.py
tax_microdata_benchmarking/utils/taxcalc_utils.py
tests/test_flat_file.py

Add back code needed to prepare Tax-Calculator input file.

Restore create_taxcalc_input_variables.py code deleted in a recent merge

---

tax_microdata_benchmarking/examination/results3.md
tax_microdata_benchmarking/examination/taxcalculator/alt_ctc_taxexp.py
tax_microdata_benchmarking/examination/taxcalculator/clp.dvars
tax_microdata_benchmarking/examination/taxcalculator/ctc.dvars
tax_microdata_benchmarking/examination/taxcalculator/puf-23.res-expect
tax_microdata_benchmarking/examination/taxcalculator/puf-26.res-expect
tax_microdata_benchmarking/examination/taxcalculator/runs.sh

Add `examination/taxcalculator/alt_ctc_taxexp.py` script that computes tax-expenditure under an alternative assumption.   There is only a very small difference between this alternative tax expenditure and the standard-assumption tax expenditure for the CTC.

Add examination alt_ctc_taxexp.py script

---

tax_microdata_benchmarking/utils/imputation.py

Responds in part to issue #135.
The remaining deprecation and performance warnings are in the `datasets/puf.py` and `datasets/uprate_puf.py` modules.

Revise Imputation code to avoid numpy deprecation warning

---

tax_microdata_benchmarking/datasets/cps.py
tax_microdata_benchmarking/datasets/puf.py
tax_microdata_benchmarking/utils/trace.py

Switch to the modern numpy random number generator and seed each random number stream to ensure tax-microdata output is reproducable.

Remove unwanted output randomness across runs

---

tax_microdata_benchmarking/utils/taxcalc_utils.py
tests/test_flat_file.py

No tax code changes; just a test enhancement.
See the revised issue #146 for details.

Add 2026 tax expenditures to output triggered by TAXEXP environ variable

---

tax_microdata_benchmarking/datasets/puf.py

Before these changes, "make test" generated 514 warnings.
After these changes, "make test" generates 472 warnings.

Remove performance warnings in puf.py code

---

tax_microdata_benchmarking/datasets/taxcalc_dataset.py

Before these changes, "make test" generated 472 warnings.
After these changes, "make test" generates 460 warnings, of which 458 are in the `policyengine-core` code as indicated here:
```
packages/policyengine_core/enums/enum.py:56: 
FutureWarning: Series.__getitem__ treating keys as positions is deprecated. 
In a future version, integer keys will always be treated as labels (consistent with DataFrame
behavior). To access a value by position, use `ser.iloc[pos]`
if isinstance(array[0], Enum):
```
This problem was reported a couple of weeks ago as [PolicyEngine-Core issue 238](https://github.com/PolicyEngine/policyengine-core/issues/238), but the offending statement has not yet been changed.

Fix warnings in taxcalc_dataset.py code

---

tax_microdata_benchmarking/datasets/taxcalc_dataset.py

These code changes should have been in PR #164.

Cosmetic changes to taxcalc_dataset.py code

---

tests/test_misc.py
tmd/create_taxcalc_input_variables.py
tmd/imputation_assumptions.py

The values of `agi_bin` will be used in the creation of subnational area sampling weights.

Add calculation of Tax-Calculator agi_bin variable

---

tests/test_misc.py
tmd/create_taxcalc_input_variables.py
tmd/imputation_assumptions.py

Because of the multitude of AGI bin definitions used in different SOI sub-national data sources.
Fixes issue #183 in part.

Remove calculation of agi_bin variable

---

tests/test_area_weights.py
tmd/areas/create_area_weights.py

The additional statistics (on `s006` and `wght_us`) show the distribution of the national weights that are the starting point of the `create_area_weights.py` logic.

Add descriptive statistics on initial weights to create_area_weights.py

---

Makefile
tests/test_area_make.py
tests/test_area_weights.py
tmd/areas/create_area_weights.py
tmd/areas/make_all.py
tmd/areas/weights/bb.log-expect

Tool for automating the creation of many area weights files.
Supports the kinds of workflows described in issue #197.

Add areas/make_all.py tool

---

tests/test_tax_expenditures.py

More pytorch `reweight` variation on a new Mac with an Apple M1 (rather than an Intel) chip.
These changes should fix the tax-expenditure test failure reported in issue #187.

Increase slightly the diff rtol in test_tax_expenditues.py

---

tmd/areas/create_area_weights.py

In response to the discussion of merged PR #203 ending with [this comment](https://github.com/PSLmodels/tax-microdata-benchmarking/commit/538aa184b1bf899168e6ea124165ee5c362d7059#commitcomment-146927065).

Reduce create_area_weights.py FTOL and GTOL value from 1e-8 to 1e-9

---

tmd/areas/create_area_weights.py
tmd/areas/make_all.py
tmd/areas/targets/xx_params.yaml

For an example, see the `areas/targets/xx_params.yaml` file.
Currently only the target_ratio_tolerance parameter can be customized.

Add ability to specify an optional area custom parameters file

---

tmd/areas/create_area_weights.py

Estimates of the 2021 population of the districts based on the 2020 Census are available from:
```
https://www2.census.gov/programs-surveys/acs/data/2021/CD118_Data_Profiles
```
where the relevant DP02 statistics are 
"ANCESTRY: Total population" or
"PLACE OF BIRTH: Total population",
both of which seem to be the same number.

Use districts of the 118th Congress in create_area_weights.py

---

tmd/areas/create_area_weights.py

Cosmetic changes in `areas/create_area_weights.py` to bring TMD district naming into line with district naming used in IRS district data files.  Also, add DC as a "state" (even though it has no senators or voting representatives in the House) because IRS provides DC congressional district data.

Designate district in states with a single Congressional district with the IRS 00 district number

---

tmd/areas/create_area_weights.py

Add several optimization parameters to the customizable PARAMS dictionary.
Change the default number of regularization loops from five to one, but this can be customized as can the initial regularization delta parameter value.  Also, fix a typo that was causing a bug.

Update create_area_weights.py script

---

tmd/areas/create_area_weights.py

Fixes #242 by implementing changes proposed in PR #244.
In the next few weeks the project will switch to using 118th Congressional districts based on the 2020 Census.

Temporarily move back to using Congressional districts based on 2010 Census

---

tmd/areas/create_area_weights.py
tmd/areas/targets/README.md

Fix area targets file specification and add targets file documentation

---

Makefile

Obsolete because this action is done as part of "make test".

Remove obsolete tax-expenditures-report Makefile target

---

tests/test_misc.py

These test results are useful in judging the sensibility of the changes in the specification of the `count` area targets file variable that were made in pull request #253.

Add test of weighted number of tax units with zero AGI

---

tmd/areas/create_area_weights.py

Removes unused code mistakenly included in PR #267.
This is a cosmetic edit that causes no change in logic.

Remove redundant code in create_area_weight.py

---

tmd/areas/targets/prepare/R/libraries.R
tmd/areas/targets/prepare/_quarto.yml
tmd/areas/targets/prepare/cd_create_basefile_for_117Congress_cd_target_files.qmd
tmd/areas/targets/prepare/cd_create_cd_117_118_crosswalk_and_cdbasefile_118.qmd
tmd/areas/targets/prepare/cd_map_tcvars_and_extract_target_files.qmd
tmd/areas/targets/prepare/index.qmd
tmd/areas/targets/prepare/usage.qmd

Data file used to create Congressional District targets now includes 117th Congressional session targets plus estimated targets for 118th Congressional session, so either kind of target file can be created.

PR prepare targets incorporate 118th session

---

tmd/areas/create_area_weights.py

This change to the `create_area_weights.py` script adds a few valid area names for the six states that gained Congressional districts after the 2020 Census redistricting and subtracts one district for the seven states that lost a district.   Here are those states:
```
GAINERS:
state,2010cds,2020cds= CO  7  8
state,2010cds,2020cds= FL 27 28
state,2010cds,2020cds= MT  1  2
state,2010cds,2020cds= NC 13 14
state,2010cds,2020cds= OR  5  6
state,2010cds,2020cds= TX 36 38
LOSERS:
state,2010cds,2020cds= CA 53 52
state,2010cds,2020cds= IL 18 17
state,2010cds,2020cds= MI 14 13
state,2010cds,2020cds= NY 27 26
state,2010cds,2020cds= OH 16 15
state,2010cds,2020cds= PA 18 17
state,2010cds,2020cds= WV  3  2
```
So, for example, after this change is merged into the master branch, `tx37` and `tx38` will …

Check area name validity using number of 118th Congressional districts

---

tmd/create_taxcalc_cached_files.py

Write all Tax-Calculator variables for TAX_YEAR to cached_allvars.csv in the storage output folder. After creating area weights, this file can be used in conjunction with those weights to analyze results for individual areas and across areas.
This PR could make tmd_2021.csv in the same folder superfluous, but does not eliminate creation of that file because that requires further investigation.

cache all variables

---

tmd/areas/chisquare_test.py

Correct documentation to state that default numbins is 200, not 100

Update chisquare_test.py docstring

---

tmd/areas/weights/examine/renv.lock

This PR only affects the R project `examine`. It makes no changes to python code and it makes no changes to substantive R code.
It simply updates the `renv.lock` file, making it easier for users to construct the R environment needed for the R project `examine`.

examine: add renv.lock

---

tmd/areas/targets/prepare/prepare_cds/R/constants.R
tmd/areas/targets/prepare/prepare_cds/cd_compare_us_totals_tmd_vs_irs_published.qmd
tmd/areas/targets/prepare/prepare_cds/cd_construct_long_soi_data_file.qmd
tmd/areas/targets/prepare/prepare_cds/cd_construct_soi_variable_documentation.qmd
tmd/areas/targets/prepare/prepare_cds/cd_create_basefile_for_117Congress_cd_target_files.qmd
tmd/areas/targets/prepare/prepare_cds/cd_create_basefile_multiple_sessions.qmd
tmd/areas/targets/prepare/prepare_cds/cd_create_cd_117_118_crosswalk_and_cdbasefile_118.qmd
tmd/areas/targets/prepare/prepare_cds/cd_create_variable_mapping.qmd
tmd/areas/targets/prepare/prepare_cds/cd_enhance_basefile_with_special_targets.qmd
tmd/areas/targets/prepare/prepare_cds/cdrecipes/phase6_add_socsec.json
tmd/areas/targets/prepare/prepare_cds/create_cdtargets.R

This PR does not change any python code.
The PR improves R code but does not make significant substantive changes.
This improves the way in which "all counts" targets are processed and stored, making it easier to create xxxx_targets.csv files that include these targets. ("all counts" targets are targets for the numbers of returns for a variable, regardless of the variable's value.)
The code still needs substantial cleanup and documentation but is substantially improved so I am creating this PR.

PR streamline targets for cd allreturns counts

---

tmd/areas/targets/prepare/prepare_states/.gitignore
tmd/areas/targets/prepare/prepare_states/R/constants.R
tmd/areas/targets/prepare/prepare_states/_quarto.yml
tmd/areas/targets/prepare/prepare_states/construct_soi_documentation.qmd
tmd/areas/targets/prepare/prepare_states/download_soi_data.qmd
tmd/areas/targets/prepare/prepare_states/get_soi_documentation.qmd
tmd/areas/targets/prepare/prepare_states/renv.lock
tmd/areas/targets/prepare/prepare_states/temp.r

This PR does not change any python code.
This PR prepares csv files with cleaned variable descriptions for each variable in state data from SOI Historical Table 2.
The code creates 2 output files that are saved in the *data/intermediate* folder. These files are not included in the repo. They will be created by the user when the project is rendered:
-  *soi_documentation_by_year.csv* has for each variable, for each year, the SOI description for that year and a uniform description across all years
- *soi_documentation.csv* has for each variable a uniform description that is general enough to apply to all years

PR prepare state variable documentation

---

tmd/areas/targets/prepare/prepare_states/R/libraries.R
tmd/areas/targets/prepare/prepare_states/SALT_analysis.qmd
tmd/areas/targets/prepare/prepare_states/_quarto.yml
tmd/areas/targets/prepare/prepare_states/combine_base_and_additional_targets.qmd
tmd/areas/targets/prepare/prepare_states/construct_long_soi_data_file.qmd
tmd/areas/targets/prepare/prepare_states/construct_soi_documentation.qmd
tmd/areas/targets/prepare/prepare_states/create_additional_state_targets.qmd
tmd/areas/targets/prepare/prepare_states/create_state_targets_basefile.qmd
tmd/areas/targets/prepare/prepare_states/enhance_state_targets_basefile.qmd
tmd/areas/targets/prepare/prepare_states/renv.lock

This PR does not change any python code.
Most state targets in this project are drawn directly from data underlying IRS SOI Historical Table 2 for 2021, which publishes summary data for each state. However, some of those values are not suitable as targets because they are not defined or measured in the way that we want for the TMD microdata.
This is especially true for itemized deductions where what we want for the TMD are the values available to be deducted for both itemizers and nonitemizers, but the SOI published values are deductions claimed by taxpayers that itemized in 2021. These values are not appropriate as targets because the number of itemizers was sharply reduced in 2021 due primarily to the TCJA's increase in the standard deduction.
This PR updates the R project …

PR add targets shared down from tmd

---

tmd/examination/2022/dbtab.sql

Remove irrelevant comment from tmd/examination/2022/dbtab.sql

---

tmd/create_taxcalc_growth_factors.py

This PR fixes the pandas `FutureWarning` about chained assignment in `create_taxcalc_growth_factors.py` while also improving performance through vectorization. (Issue #373.)
The original code used chained assignment that will break when pandas 3.0 makes Copy-on-Write the default:
```python
for idx in range(0, num_rows):
added.YEAR.iat[idx] = last_puf_year + idx + 1  # Chained assignment
```
This generated warnings on some systems and will fail silently in pandas 3.0.
Replaced the loop with a vectorized numpy approach:
added = added.reset_index(drop=True)  # guardrail
added.loc[:, 'YEAR'] = np.arange(last_puf_year + 1, last_puf_year + 1 + num_rows)
- ✅ Eliminates pandas warning - No more ChainedAssignmentError
- ✅ 6x performance improvement due to vectorization (but loop did not take much …

PR fix pandas chained assignment
