setup.py

Need newer version of Tax-Calculator to conduct data examination tasks.

Use a more up-to-date version of taxcalc

---

tax_microdata_benchmarking/create_flat_file.py

Add net capital gains and WIC variables

---

tax_microdata_benchmarking/examination/methods.md
tax_microdata_benchmarking/examination/results.md

This PR adds text that clarifies the model and dataset versions used in Phase 1 examination.

Minor edits to the methods.md and results.md examination documents

---

tax_microdata_benchmarking/examination/results2.md

This pull request is strictly cosmetic.

Reformat tables in the results2.md document

---

tax_microdata_benchmarking/examination/methods.md

Rename Phase 2 res-expect files in examination/methods.md

---

tax_microdata_benchmarking/examination/taxcalculator/runs.sh

Generalizes the `runs.sh` script.

Update examination/taxcalculator/runs.sh script to handle Phase 2 and 3 datasets

---

tax_microdata_benchmarking/adjust_qbi.py
tax_microdata_benchmarking/create_flat_file.py

Dataset update

---

README.md

A test to see if this PR passes all the tests on GitHub.

Minor edit of README.md document

---

Makefile
README.md
tax_microdata_benchmarking/create_all_datasets.py

This PR adds to the README and simplifies the number of steps needed to replicate the GitHub actions' runs.

Simplify setup process and add docs

---

tax_microdata_benchmarking/create_taxcalc_input_variables.py

Original (that is, pre-reweighting) weights added to facilitate data examination activities.

Add optional s006_original variable to the tmd.csv file

---

setup.py
tax_microdata_benchmarking/create_taxcalc_input_variables.py
tax_microdata_benchmarking/datasets/cps.py
tax_microdata_benchmarking/datasets/puf.py
tax_microdata_benchmarking/datasets/taxcalc_dataset.py
tax_microdata_benchmarking/datasets/tmd.py
tax_microdata_benchmarking/datasets/uprate_puf.py
tax_microdata_benchmarking/imputation_assumptions.py
tax_microdata_benchmarking/utils/imputation.py
tax_microdata_benchmarking/utils/pension_contributions.py
tax_microdata_benchmarking/utils/qbi.py
tax_microdata_benchmarking/utils/reweight.py

Makes changes in the TMD repository necessary to fix issue #103.
It appears as if the use of the PolicyEngine `survey_enhance` package (which was introduced by PR #90) is a cause of the problem reported in issue #103.  This is so because the `survey_enhance` Imputation class does not have the capability of producing the same imputation results each time it is executed using the same data.  The plan is to incorporate an Imputation class directly in this repository so that it can be revised to meet our requirement that imputation results are reproducible across model runs.

Make changes necessary to fix issue 103

---

tax_microdata_benchmarking/datasets/puf.py
tax_microdata_benchmarking/datasets/taxcalc_dataset.py
tax_microdata_benchmarking/datasets/tmd.py
tax_microdata_benchmarking/utils/trace.py

Fixes #111.
Fixes #100 by implementing the first option in [this comment](https://github.com/PSLmodels/tax-microdata-benchmarking/issues/100#issuecomment-2189114805) by @donboyd5.

Fixes problem reported in issue #111

---

tax_microdata_benchmarking/datasets/tmd.py
tax_microdata_benchmarking/utils/taxcalc_utils.py
tests/tax_expenditure_targets.yaml
tests/test_flat_file.py

Fix tests/test_flat_file.py tax expenditure tests

---

tax_microdata_benchmarking/utils/trace.py

No substantive changes; just broadening scope of the `trace1` function.

Add CTC to utils/trace.py logic

---

tax_microdata_benchmarking/examination/results3.md

This pull request changes no code; it only adds to the `examination/results3.md` document.

Add discussion of credit participation rates to examination/results3.md

---

tax_microdata_benchmarking/examination/results3.md

Changes in documentation only.

Fix results.md typos

---

Dockerfile
tests/test_tmd_files.py

Remove Dockerfile

---

tmd/utils/trace.py

In order to better assess the quality of the data-construction process.

Add population, pension contribution, and income tax tracing

---

tests/test_create_tmd_variables.py
tmd/utils/reweight.py

Defragment loss_matrix in the reweight.py module

---

tmd/areas/create_area_weights.py

Cosmetic changes to create_area_weights.py code

---

tmd/areas/create_area_weights.py

This completes the initial development of the `create_area_weights.py` module.

Add code to write area weights file to create_area_weights.py module

---

tmd/areas/create_area_weights.py

Reduce regularization `delta` value repeatedly until all targets are hit.
Final loop has `delta`=0 in which case target misses indicate targets are inconsistent.

Add regularization loop to create_area_weights.py

---

tests/test_area_weights.py
tmd/areas/create_area_weights.py

No changes in logic, just adds logging flexibility.

Revise create_area_weights.py to log to stdout or a log file

---

tests/test_area_weights.py

No substantive changes in the test.

Minor change in test_area_weights.py module

---

tmd/areas/examine/README.md
tmd/areas/prepare/README.md

Should have been included in PR #210.

Add two more area-related README.md files

---

tmd/areas/targets/prepare/README.md
tmd/areas/weights/examine/README.md

Issue #197 identifies the follow area activities:
> 1. Automating creation of multiple sets of weights
> 2. Pre-optimization identification of potential problems and possible pre-optimization adjustments
> 3. Post-optimization diagnosis of actual problems
PR #200 (and subsequent improvement PRs) implement the first item in the above list by adding a `make_all.py` script that emulates a Makefile by creating area weights files for new area targets files.
This PR sets up the `areas/targets/prepare/` folder where item 2 activity including creating the area `areas/targets/*_targets.csv` files can be conducted.
This PR also sets up the `areas/weights/examine/` folder where item 3 activity can be conducted using the `areas/weights/` log and weights files.

Better organize areas folder structure to align with issue #197

---

tmd/datasets/tmd.py

Fixes #140 by sorting the dataframe columns before writing to a CSV-formatted file.

Sort columns of dataframe written to tmd_2021.csv

---

tmd/areas/create_area_weights.py

Remove disp key from scipy.minimize options dictionary

---

tmd/areas/create_area_weights.py
tmd/areas/make_all.py

Implement a binary cache of AGI values to speed up the areas/make_all.py scipt

---

.gitignore
tmd/areas/create_area_weights.py
tmd/areas/make_all.py

These changes improve error messages and broaden the number of faux areas that can be used in testing.

Improve handling of area validity checking in create_area_weights.py

---

tmd/areas/create_area_weights.py

No change in area weighting logic.

Switch to using 118th Congressional Districts

---

tmd/areas/create_area_weights.py

Minor adjustment to the `create_area_weights.py` script.

Raise TARGET_RATIO_TOLERANCE from 0.001 to 0.004

---

tmd/areas/make_all.py

Brings code into line with decision to use 118th Congress districts based on 2020 Census.

Add valid_area checking to the make_all.py script

---

tmd/areas/create_area_weights.py

Enhances ability to identify a troublesome target amount.

Add ability to comment out one or more lines in a targets file

---

Makefile
tmd/datasets/tmd.py

Ensure RECID values are unique

---

tmd/areas/create_area_weights.py
tmd/storage/output/README.md

Add warning about tmd_2021.csv file to the tmd/storage/output/README.md file

---

tmd/areas/targets/README.md

Format changes to areas/targets/README.md documentation

---

tmd/areas/targets/prepare/README.md
tmd/areas/weights/examine/README.md

The documentation will be evolving to reflect progress in the project.

Add links to areas preparation and examination documentation

---

tmd/create_taxcalc_cached_files.py
tmd/utils/taxcalc_utils.py

These changes should have been included in PR #288.

Add more uses of Tax-Calculator Policy.tmd_constructor

---

Makefile
pyproject.toml

Changes are same as those recently implemented in the [Tax-Calculator project](https://github.com/PSLmodels/Tax-Calculator).

Add pyproject.toml file and simplify 'make install' Makefile logic

---

tmd/examination/results4.md

No change in examination results.

Update  Tax-Calculator version and date in examination/results4.md

---

tmd/areas/weights/examine/R/functions_constants.R
tmd/areas/weights/examine/R/render_all.R
tmd/areas/weights/examine/README.md
tmd/areas/weights/examine/_area-template_dt.qmd
tmd/areas/weights/examine/_quarto.yml
tmd/areas/weights/examine/_quarto_template.yml
tmd/areas/weights/examine/data_preparation.qmd
tmd/areas/weights/examine/summary_analysis.qmd
tmd/areas/weights/examine/variables_analyzed.qmd

This PR does not change any python code.
Its primary purpose is to improve documentation for the R project `examine`, which examines results. It updates the examine README to explain how to run the code.
It includes very minor changes to some R code, simply to improve presentation of tables.

PR improve documentation for examine

---

tmd/areas/weights/examine/variables_analyzed.qmd

No impact on results. Just fixes a typo.

Fix typo in variables_analyzed.qmd

---

README.md

Add link to documentation on using TMD files with Tax-Calculator

---

tmd/examination/2022/results.md

Minor clarifying edit of tmd/examination/2022/results.md file

---

tmd/examination/2022/bootstrap_sampling.py
tmd/examination/2022/precision.sh
tmd/examination/2022/precvars

The added files help gauge the degree of sampling uncertainty involved in the 2022 examination work.

Add tmd/examination/2022/precision.sh script and associated files

---

tmd/examination/2022/sampling_variability.py

No changes in Python code that generates the TMD files.

Add tmd/examination/2022/sampling_variability.py script

---

setup.py
tmd/examination/2022/results.md

Minor changes in three of the six state results.

Update 2022 examination results using Tax-Calculator version 4.4.1

---

tmd/utils/reweight.py

Addresses #366. Prepared by Claude with oversight and direction by me. I copy Claude's PR comment below, lightly edited by me.
This PR adds GPU acceleration with automatic GPU detection to the national weight optimization process in `tmd/utils/reweight.py`, providing **5x or more performance improvement** on CUDA-capable systems while maintaining full backward compatibility.
**Benchmark Results** (NVIDIA GeForce GTX 1070 Ti):
- **CPU (Master)**: 4m25s optimization time, ~7.7 iterations/second
- **GPU (This PR)**: 45s optimization time, ~50 iterations/second  
- **Overall Speedup**: **5+x faster**
- Detects CUDA availability automatically
- Falls back to CPU gracefully if GPU unavailable
- No configuration required
- New optional parameter `use_gpu: bool = True` in `reweight()` function
- …

Add GPU Acceleration for National Weight Optimization

---

gitpr
gitsync
tmd/national_targets/r/libraries.R

Further streamlining for situation in which there is just GitHub repo and a local cloned repo.

More git script modifications
